"""
app.py — Flask web UI for PrivacyShield
Upload a PDF → process it → download the result.
"""
import sys
import os

# Force venv site-packages using absolute path
venv_site_packages = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'venv', 'Lib', 'site-packages')
if venv_site_packages not in sys.path:
    sys.path.insert(0, venv_site_packages)

import uuid
from io import BytesIO
from pathlib import Path

from flask import (
    Flask,
    render_template,
    request,
    send_file,
    jsonify,
)

from privacyshield.key_manager.encryptor import (
    generate_key,
    key_to_string,
    string_to_key,
    encrypt_bytes,
)
from privacyshield.key_manager.decryptor import decrypt_bytes

app = Flask(__name__, template_folder="privacyshield/templates")
app.config["MAX_CONTENT_LENGTH"] = 50 * 1024 * 1024  # 50 MB limit

UPLOAD_DIR = Path("uploads")
OUTPUT_DIR = Path("outputs")
UPLOAD_DIR.mkdir(exist_ok=True)
OUTPUT_DIR.mkdir(exist_ok=True)

PAYLOAD_MARKER = b"\n%%PRIVACYSHIELD_ENCRYPTED_ORIGINAL_V1%%\n"


def _safe_unlink(path: Path) -> None:
    try:
        path.unlink(missing_ok=True)
    except Exception:
        pass


def _embed_encrypted_original(redacted_pdf_path: Path, original_pdf_path: Path, key: bytes) -> None:
    original_bytes = original_pdf_path.read_bytes()
    encrypted_payload = encrypt_bytes(original_bytes, key)
    with redacted_pdf_path.open("ab") as f:
        f.write(PAYLOAD_MARKER)
        f.write(encrypted_payload)


def _extract_encrypted_payload(redacted_pdf_bytes: bytes) -> bytes:
    marker_idx = redacted_pdf_bytes.rfind(PAYLOAD_MARKER)
    if marker_idx == -1:
        raise ValueError(
            "No encrypted payload found in this PDF. "
            "Use a redacted file generated by PrivacyShield."
        )
    payload = redacted_pdf_bytes[marker_idx + len(PAYLOAD_MARKER):].strip()
    if not payload:
        raise ValueError("Encrypted payload is empty or corrupted.")
    return payload


# ── routes ────────────────────────────────────────────────────────────────────

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/upload", methods=["POST"])
def upload():
    if "file" not in request.files:
        return jsonify({"error": "No file part in the request."}), 400

    file = request.files["file"]
    if file.filename == "":
        return jsonify({"error": "No file selected."}), 400

    if not file.filename.lower().endswith(".pdf"):
        return jsonify({"error": "Only PDF files are accepted."}), 400

    job_id = uuid.uuid4().hex
    original_name = file.filename
    safe_stem = Path(original_name).stem
    upload_path = UPLOAD_DIR / f"{job_id}.pdf"
    file.save(str(upload_path))

    output_path = OUTPUT_DIR / f"{job_id}_redacted.pdf"
    shield_path = OUTPUT_DIR / f"{job_id}.privacyshield"

    try:
        # Re-insert venv path inside request context to be safe
        venv_sp = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'venv', 'Lib', 'site-packages')
        if venv_sp not in sys.path:
            sys.path.insert(0, venv_sp)

        from privacyshield.reconstructor.pdf_merger import redact_pdf

        key_string = redact_pdf(
            input_pdf_path=str(upload_path),
            output_pdf_path=str(output_path),
            shield_path=str(shield_path),
        )
    except Exception as e:
        _safe_unlink(upload_path)
        _safe_unlink(output_path)
        _safe_unlink(shield_path)
        return jsonify({"error": f"Redaction pipeline failed: {e}"}), 500

    if key_string:
        key = string_to_key(key_string)
    else:
        key = generate_key()
        key_string = key_to_string(key)

    _embed_encrypted_original(output_path, upload_path, key)

    return jsonify({
        "job_id": job_id,
        "original_name": original_name,
        "download_name": f"{safe_stem}_redacted.pdf",
        "encryption_key": key_string,
    })


@app.route("/download/<job_id>")
def download(job_id):
    if not job_id.isalnum():
        return jsonify({"error": "Invalid job id."}), 400

    output_path = OUTPUT_DIR / f"{job_id}_redacted.pdf"
    shield_path = OUTPUT_DIR / f"{job_id}.privacyshield"
    upload_path = UPLOAD_DIR / f"{job_id}.pdf"

    if not output_path.exists():
        return jsonify({"error": "File not found. It may have expired."}), 404

    download_name = request.args.get("name", "redacted.pdf")

    pdf_bytes = output_path.read_bytes()
    _safe_unlink(output_path)
    _safe_unlink(shield_path)
    _safe_unlink(upload_path)

    return send_file(
        BytesIO(pdf_bytes),
        as_attachment=True,
        download_name=download_name,
        mimetype="application/pdf",
    )


@app.route("/preview/<job_id>/<variant>")
def preview(job_id, variant):
    if not job_id.isalnum():
        return jsonify({"error": "Invalid job id."}), 400

    if variant == "original":
        pdf_path = UPLOAD_DIR / f"{job_id}.pdf"
    elif variant == "redacted":
        pdf_path = OUTPUT_DIR / f"{job_id}_redacted.pdf"
    else:
        return jsonify({"error": "Invalid preview variant."}), 400

    if not pdf_path.exists():
        return jsonify({"error": "Preview file not found."}), 404

    return send_file(str(pdf_path), mimetype="application/pdf")


@app.route("/restore", methods=["POST"])
def restore_original():
    if "file" not in request.files:
        return jsonify({"error": "No redacted PDF provided."}), 400

    key_str = (request.form.get("key") or "").strip()
    if not key_str:
        return jsonify({"error": "No decryption key provided."}), 400

    redacted_file = request.files["file"]
    if redacted_file.filename == "":
        return jsonify({"error": "No file selected."}), 400

    if not redacted_file.filename.lower().endswith(".pdf"):
        return jsonify({"error": "Only PDF files are accepted."}), 400

    try:
        redacted_bytes = redacted_file.read()
        encrypted_payload = _extract_encrypted_payload(redacted_bytes)
        original_pdf_bytes = decrypt_bytes(encrypted_payload, key_str)
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    except Exception:
        return jsonify({"error": "Failed to restore original PDF."}), 500

    restore_id = uuid.uuid4().hex
    safe_stem = Path(redacted_file.filename).stem
    output_path = OUTPUT_DIR / f"{restore_id}_restored.pdf"
    output_path.write_bytes(original_pdf_bytes)

    return jsonify({
        "restore_id": restore_id,
        "download_name": f"{safe_stem}_original.pdf",
    })


@app.route("/download-restored/<restore_id>")
def download_restored(restore_id):
    if not restore_id.isalnum():
        return jsonify({"error": "Invalid restore id."}), 400

    restored_path = OUTPUT_DIR / f"{restore_id}_restored.pdf"
    if not restored_path.exists():
        return jsonify({"error": "File not found."}), 404

    download_name = request.args.get("name", "original.pdf")

    pdf_bytes = restored_path.read_bytes()
    _safe_unlink(restored_path)

    return send_file(
        BytesIO(pdf_bytes),
        as_attachment=True,
        download_name=download_name,
        mimetype="application/pdf",
    )


@app.route("/preview-restored/<restore_id>")
def preview_restored(restore_id):
    if not restore_id.isalnum():
        return jsonify({"error": "Invalid restore id."}), 400

    restored_path = OUTPUT_DIR / f"{restore_id}_restored.pdf"
    if not restored_path.exists():
        return jsonify({"error": "File not found."}), 404

    return send_file(str(restored_path), mimetype="application/pdf")


if __name__ == "__main__":
    app.run(debug=False, port=5000)