"""
unredact.py
-----------
POST /unredact — accepts redacted PDF + key, restores original
"""

import uuid
from pathlib import Path

from fastapi import APIRouter, UploadFile, File, Form, HTTPException
from fastapi.responses import FileResponse

from privacyshield.key_manager.decryptor import decrypt_bytes

router = APIRouter()

OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)

PAYLOAD_MARKER = b"\n%%PRIVACYSHIELD_ENCRYPTED_ORIGINAL_V1%%\n"


def _extract_encrypted_payload(redacted_pdf_bytes: bytes) -> bytes:
    marker_idx = redacted_pdf_bytes.rfind(PAYLOAD_MARKER)
    if marker_idx == -1:
        raise ValueError(
            "No encrypted payload found in this PDF. "
            "Use a redacted file generated by PrivacyShield."
        )
    payload = redacted_pdf_bytes[marker_idx + len(PAYLOAD_MARKER):].strip()
    if not payload:
        raise ValueError("Encrypted payload is empty or corrupted.")
    return payload


def _safe_unlink(path: Path) -> None:
    try:
        path.unlink(missing_ok=True)
    except Exception:
        pass


@router.post("/unredact")
async def unredact_document(
    file: UploadFile = File(...),
    key: str = Form(...),
):
    """
    Accept a redacted PDF + encryption key, restore original PDF.
    """
    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are accepted.")

    if not key.strip():
        raise HTTPException(status_code=400, detail="No decryption key provided.")

    try:
        redacted_bytes = await file.read()
        encrypted_payload = _extract_encrypted_payload(redacted_bytes)
        original_pdf_bytes = decrypt_bytes(encrypted_payload, key.strip())
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception:
        raise HTTPException(status_code=500, detail="Failed to restore original PDF.")

    restore_id = uuid.uuid4().hex
    safe_stem = Path(file.filename).stem
    output_path = OUTPUT_DIR / f"{restore_id}_restored.pdf"
    output_path.write_bytes(original_pdf_bytes)

    return {
        "restore_id": restore_id,
        "download_name": f"{safe_stem}_original.pdf",
    }


@router.get("/download-restored/{restore_id}")
def download_restored(restore_id: str, name: str = "original.pdf"):
    """Download the restored original PDF."""
    if not restore_id.isalnum():
        raise HTTPException(status_code=400, detail="Invalid restore id.")

    restored_path = OUTPUT_DIR / f"{restore_id}_restored.pdf"
    if not restored_path.exists():
        raise HTTPException(status_code=404, detail="File not found.")

    return FileResponse(
        path=str(restored_path),
        filename=name,
        media_type="application/pdf",
    )